name: serotyper
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.13.5
  - pip
  - blast=2.16.0
  - pip:
      - scikit-learn==1.8.0
      - numpy==2.4.3
      - scipy==1.17.1
      - joblib==1.5.3
      - threadpoolctl==3.6.0
      - biopython==1.86
      - mmh3==5.2.1
      - screed==1.2.0
